@baseURL=http://localhost:8000
@token =eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3OTEzODIxNDEsImV4cCI6MTc5MTM4NTc0MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiYWRtaW5AYWRtaW4uY29tIn0.d7FnlL8XKNbIjMVcAvrPPwVgyh8I_55-J2UZq0tlxAZ8obmgBQe7G3-aLT967ClEGtI2u1_kQ1mxlDWQJ8K2IBYVVnIW2cNKFvJK1urQ9ak_68DnLol1m77maoNEUiqU9nx0Ah7bhcGIfu9VkQ2itHcCkpbAdJ0wLdBw8FgatJ7Ivo5FbAekT_l2beDncv6f37k_9EXOeiEB4bkwTExtYPSp1TBrqu_W4qgjxXynb3KIgaC9ecJm2mTKRlVDnDGGRkO5N2M3E6Hvs2WMoercZv5-tyf9TFSwHKA0RWfxw7U-8c2tfkVums7L320bFMqsmFObc--qLhlMMiYlHiHTuQ
### Listing resources

POST {{baseURL}}/movies
Content-Type: application/json

{
  "title": "Test Movie",
  "description": "A test movie for API testing"
}

POST {{baseURL}}/movies/create
Content-Type: application/json

{
  "titre": "Test",
  "description": "A test movie for API testing",
  "year": 2024,
  "categories": [
    {
      "id": 1
    }
  ]
}

POST {{baseURL}}/movies/read
Content-Type: application/json

{
  "id": 5
}

POST {{baseURL}}/movies/delete
Content-Type: application/json

{
  "id": 6
}

POST {{baseURL}}/movies/update
Content-Type: application/json

{
  "id": 5,
  "titre": "Updated Test Movie",
  "description": "An updated test movie for API testing",
  "year": 2024,
  "categories": [
    {
      "id": 1
    }
  ]
}


### Authenticate

POST {{baseURL}}/api/login_check
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "password"
}

> {% client.global.set("token",response.body.token); %}

### Test get user

GET {{baseURL}}/api/user
Authorization: Bearer {{token}}

GET {{baseURL}}/movies/list?page=2&limit=2

POST {{baseURL}}/api/ratings
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "movieId": 3,
    "rating": 1
}
PUT {{baseURL}}/api/ratings/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "rating": 1
}
GET {{baseURL}}/api/ratings
Authorization: Bearer {{token}}