@baseURL=http://localhost:8000
### Listing resources

GET {{baseURL}}/movies
GET {{baseURL}}/movies?title=my
GET {{baseURL}}/movies?year=2026
GET {{baseURL}}/movies?title=my&year=1932
GET {{baseURL}}/movies?page=2&limit=2
GET {{baseURL}}/movies?title=o&page=2&limit=1

GET {{baseURL}}/movies/1
Content-Type: application/json

POST {{baseURL}}/movies/create
Content-Type: application/json

{
  "title": "Test3",
  "description": "A test movie for API testing",
  "year": 2024,
  "categories": [
    {
      "id": 3
    }
  ]
}

POST {{baseURL}}/movies/read
Content-Type: application/json

{
  "id": 100
}

DELETE {{baseURL}}/movies/delete
Content-Type: application/json

{
  "id": 15
}

PUT {{baseURL}}/movies/update
Content-Type: application/json

{
  "id": 16,
  "title": "Test2",
  "description": "An updated test movie for API testing",
  "year": 2024,
  "categories": [
    {
      "id": 1
    }
  ]
}


### Authenticate

POST {{baseURL}}/api/login_check
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "password"
}

> {% client.global.set("token",response.body.token); %}

### Test get user

GET {{baseURL}}/api/user
Authorization: Bearer {{token}}

POST {{baseURL}}/api/ratings
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "movieId": 63,
    "rating": 3
}
PUT {{baseURL}}/api/ratings/10
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "rating": 2
}
GET {{baseURL}}/api/ratings
Authorization: Bearer {{token}}

DELETE {{baseURL}}/api/ratings/3
Authorization: Bearer {{token}}

GET {{baseURL}}/api/movies/list
Authorization: Bearer {{token}}

GET {{baseURL}}/api/movies/list?page=1&limit=4
Authorization: Bearer {{token}}

POST {{baseURL}}/api/users/3/follow
Authorization: Bearer {{token}}

GET {{baseURL}}/api/users
Authorization: Bearer {{token}}

DELETE {{baseURL}}/api/users/2/follow
Authorization: Bearer {{token}}




